In [3]:

from src.constants import REGMKT_END_TIME_NS, REGMKT_START_TIME_NS, INTERVAL_SEC
from src.constants import T_N, R_N, A_N, TICKER_SYM, DATE_FROM_PATH, START_TIME_NS, END_TIME_NS, INTERVAL_NS

from collections import namedtuple
from logging import raiseExceptions
import os
import pandas as pd
import numpy as np

from pathlib import Path
from src.lib import Exchange
import zstandard
from pathlib import Path
import json

import time
from datetime import datetime, timedelta
import copy
# from utils import normalize_max

In [5]:
def load_json_zst(path: Path):
    return json.loads(zstandard.decompress(Path(path).expanduser().read_bytes()))
sym = "SPY"
date = "S061623-v50"
data_dir = '/media/seyeon04299/HardDisk/jupyter_server/parsed_itch_data/'

market_stat = load_json_zst(data_dir + f"{date}/{sym}.json.zst")


In [8]:
market_stat.keys()

dict_keys(['total_volume', 'pre_market_volume', 'regular_market_volume', 'post_market_volume', 'regular_market_start', 'post_market_start', 'stock_directory', 'opening_cross_price', 'opening_cross_volume', 'closing_cross_price', 'closing_cross_volume', 'interval_bid_execute_volume', 'interval_ask_execute_volume', 'interval_bid_execute_volume_ts', 'interval_ask_execute_volume_ts', 'interval_bid_cancel_volume', 'interval_ask_cancel_volume', 'interval_bid_add_volume', 'interval_ask_add_volume', 'interval_price_volume', 'interval_high', 'interval_high_ts', 'interval_low', 'interval_low_ts', 'interval_midprice', 'interval_midprice_ts', 'interval_open', 'interval_open_ts', 'interval_close', 'interval_close_ts', 'interval_bid_execute_msg_count', 'interval_ask_execute_msg_count', 'interval_bid_cancel_msg_count', 'interval_ask_cancel_msg_count', 'interval_bid_add_msg_count', 'interval_ask_add_msg_count', 'lob_ts', 'lob_bid_price', 'lob_bid_shares', 'lob_ask_price', 'lob_ask_shares', 'add_bid_pr

In [16]:
interval_open = np.array(market_stat["interval_open"], dtype=np.double)                                 # (57660, )
interval_high = np.array(market_stat["interval_high"], dtype=np.double)                                 # (57660, )
interval_low = np.array(market_stat["interval_low"], dtype=np.double)                                   # (57660, )
interval_close = np.array(market_stat["interval_close"], dtype=np.double)    
regmkt_interval_open = interval_open[R_N:A_N] / 1e4
regmkt_interval_high = interval_high[R_N:A_N] / 1e4
regmkt_interval_low = interval_low[R_N:A_N] / 1e4
regmkt_interval_close = interval_close[R_N:A_N] / 1e4

In [ ]:
for open,high,low,close in zip(regmkt_interval_open,regmkt_interval_high,regmkt_interval_low,regmkt_interval_close):
    

In [17]:
regmkt_interval_open

array([443.06, 443.07, 443.15, ..., 439.21, 439.34, 439.25])

In [18]:
regmkt_interval_high

array([443.12, 443.1 , 443.17, ..., 439.33, 439.34, 439.48])

In [19]:
regmkt_interval_low

array([443.04, 442.99, 443.11, ..., 439.21, 439.23, 439.25])

In [20]:
regmkt_interval_close

array([443.04, 443.1 , 443.11, ..., 439.33, 439.23, 439.43])

In [21]:
ibkr_data_dir = "/media/seyeon04299/HardDisk/jupyter_server/npy_ibkr_parsed_data/"

tmp_data = np.load(os.path.join(ibkr_data_dir,f"S{'061623'}-v50", "input_SPY_OHLCVT_ATR.npy"))


In [22]:
tmp_data[:,0]

array([443.01, 443.06, 443.11, ..., 439.21, 439.33, 439.25])

In [23]:
tmp_data[:,1]

array([443.13, 443.15, 443.18, ..., 439.33, 439.34, 439.49])

In [24]:
tmp_data[:,2]

array([442.95, 442.99, 443.04, ..., 439.21, 439.23, 439.25])